### ISSUE TITLE
Use intellij runs not runclient

### ISSUE THREAD

**Issue by TymanWasTaken** [skyblock-tools/skyhouse-mod#4]
Using intellij runs (from the gradle `genIntellijRuns` task) is so much better than using runClient as it appears you currently do. First of all, the way you use runClient right now it makes it so you can't build without a login file, and also it takes a bunch of unneeded space in the build.gradle with login/dcevm code

If you used intellij runs I don't think any of that big chunk of code would be needed

thanks for coming to my ted talk

**Comment by TymanWasTaken** [comment]
For the login part, you can directly pass --username and --password in intellij run settings, and for dcevm, use HotSwapAgent plugin in intellij

**Comment by Septikai** [comment]
done
